[package]
name = "ya-client"
version = "0.3.0"
description = "Yagna REST API client async binding"
authors = ["Golem Factory <contact@golem.network>"]
homepage = "https://github.com/golemfactory/ya-client"
repository = "https://github.com/golemfactory/ya-client"
license = "LGPL-3.0"
edition = "2018"

[features]
default = []
cli = ['structopt']
sgx=['secp256k1', 'openssl', 'secp256k1/serde', 'secp256k1/rand', 'ya-client-model/sgx']

[workspace]
members = [
    "model",
]

[dependencies]
ya-client-model = { path = "model" }

awc = "1.0"
backtrace = "0.3"
bytes = "0.5"
chrono = "0.4"
envy = "0.4"
failure = "0.1.6"
futures = "0.3"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
structopt = { version = "0.3.12", optional = true }
thiserror = "1.0"
url = "2.1"

secp256k1={ version = "0.17.2", optional=true }
openssl= { version="0.10", optional=true }
base64 = { version = "0.12.3", optional = true}
rand = "0.6"

[dev-dependencies]
actix-rt = "1.0"
env_logger = "0.7"
structopt = "0.3"
